github-apply, Error on no args (#18013)
* github-apply, Error on no args

* whitespace

* Update github-apply

I noticed the pull request number being used wasn't 5926 which is what's in the examples given for PRs.

---------

Co-authored-by: Neil Lathwood <gh+n@laf.io>

diff --git a/scripts/github-apply b/scripts/github-apply
--- a/scripts/github-apply
+++ b/scripts/github-apply
@@ -2,11 +2,17 @@
 
 LIBRENMS_DIR=$(dirname "$(readlink -f "$0/..")")
 cd "$LIBRENMS_DIR" || exit
+
+if [ $# -eq 0 ]; then
+    echo "Error: You must specify a PR number to apply a patch"
+    exit 1
+fi
+
 for pr in "$@"
     do
         case $pr in
         ''|*[!0-9]*) echo "Error: You must specify a PR number to apply a patch" ;;
-        9526) echo "Error: 9526 is just an example PR number. Please specify the actual PR number you want to apply." ;;
+        5926) echo "Error: 5926 is just an example PR number. Please specify the actual PR number you want to apply." ;;
         *) curl -s https://patch-diff.githubusercontent.com/raw/librenms/librenms/pull/"${pr}".diff | git apply --exclude=*.png -v && php artisan optimize:clear ;;
     esac
 done
