github-apply, Error on no args

diff --git a/scripts/github-apply b/scripts/github-apply
--- a/scripts/github-apply
+++ b/scripts/github-apply
@@ -2,6 +2,13 @@
 
 LIBRENMS_DIR=$(dirname "$(readlink -f "$0/..")")
 cd "$LIBRENMS_DIR" || exit
+
+
+if [ $# -eq 0 ]; then
+    echo "Error: You must specify a PR number to apply a patch"
+    exit 1
+fi
+
 for pr in "$@"
     do
         case $pr in
